apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: loginwebapp
spec:
  selector:
    matchLabels:
      app: loginwebapp
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: loginwebapp
    spec:
      containers:
        - name: loginwebapp
          image: ankushmohite/loginwebapp # Image that will be used to containers in the cluster
          
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
          volumeMounts:
            - name: velpod
              mountPath: "/tmp/hemant"

      volumes:
        - name: velpod
          hostPath:
            path: /mnt            
---
apiVersion: v1
kind: Service
metadata:
  name: login-svc
spec:
  selector:
    app: loginwebapp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30111
  type: NodePort
